version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - zookeeper-volume-data:/bitnami/zookeeper/data
      - zookeeper-volume-datalog:/bitnami/zookeeper/datalog
      - zookeeper-volume-logs:/bitnami/zookeeper/logs
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/logs
      - KAFKA_CFG_LOG_RETENTION_MS=604800000  # Mant√©m logs por 7 dias
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-volume:/var/lib/kafka/data
      - kafka-volume-logs:/bitnami/kafka/logs
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8889:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-ui
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  jupyter:
    image: custom-datascience-notebook:python-3.8.4
    container_name: custom-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks:rw
      - ./data/:/home/jovyan/work/data:rw
      - ./py/:/home/jovyan/work/py:rw
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      ENV: "local"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

volumes:
  kafka-volume:
    external: false
  kafka-volume-logs:
    external: false
  zookeeper-volume-data:
    external: false
  zookeeper-volume-datalog:
    external: false
  zookeeper-volume-logs:
    external: false
